# Generated by Django 4.2.24 on 2025-09-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.URLField(blank=True, null=True, verbose_name="Profile URL"),
        ),
    ]
