# Generated by Django 4.2.24 on 2025-09-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_groups_remove_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
