# Generated by Django 5.2.6 on 2025-09-08 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agrovets",
            field=models.ManyToManyField(
                blank=True,
                related_name="registered_farmers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
