# Generated by Django 5.2.6 on 2025-09-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_agrovets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="agrovets",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
    ]
