# Generated by Django 5.2.6 on 2025-09-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MCU",
            fields=[
                ("mcu_id", models.AutoField(primary_key=True, serialize=False)),
                ("device_id", models.CharField(max_length=50, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[("chicks", "Chicks"), ("chickens", "Chickens")],
                        default="chickens",
                        max_length=20,
                    ),
                ),
                (
                    "temp_threshold_min",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "temp_threshold_max",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "humidity_threshold_min",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "humidity_threshold_max",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
    ]
