# Generated by Django 5.2.6 on 2025-09-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_mcu_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcu',
            name='device_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
