# Generated by Django 4.2.24 on 2025-09-10 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0003_mcu_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcu",
            name="device_name",
        ),
    ]
