# Generated by Django 4.2.24 on 2025-09-10 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0005_mcu_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcu",
            name="user_id",
        ),
    ]
