# Generated by Django 5.2.6 on 2025-09-12 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                ("sensor_data_id", models.AutoField(primary_key=True, serialize=False)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("timestamp", models.DateTimeField()),
                (
                    "device_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.mcu",
                    ),
                ),
            ],
        ),
    ]
