# Generated by Django 4.2.24 on 2025-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_relaystatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="relaystatus",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
